### PR TITLE
chore: set up autopublish

### PR DESCRIPTION
**Pull request by marcoscaceres**
Don't merge yet... once we have a shortname and the FPWD is up, we should be able to auto-publish to TR going forward.

### CODE REVIEW

**Comment by siusin** [comment]
The First WG-Note has been published -> https://www.w3.org/TR/manifest-app-info/.

Can we merge this PR or should we wait for a consensus to switch to gh-pages?

**Comment by marcoscaceres** [comment]
Good news! looks like Github now allows main to serve the main branch... just set it up and works! So, no need to wait.

**Comment by marcoscaceres** [comment]
@siusin, can you confirm the IPR bot is set up properly? I don't see it in the branch protection list in settings?

**Comment by marcoscaceres** [comment]
@siusin if everything looks good to you, please feel free too merge :) Everything should work from there 🤞

**Comment by siusin** [comment]
@marcoscaceres I enabled the IPR bot earlier today so it should work for the future PRs (not for this one, unfortunately).

**Pull request merged**
